이벤트 접수정보 수정기능(회원 주소 업데이트 기능 추가)
f-lab-edu/event-recommender-festa pull request #69
Opened 2020-12-24 15:39 UTC by Jane096

참여자가 **이벤트 접수 후 자신의 정보를 수정하는 기능** 인데 회원정보 수정 기능을 사용하는게 맞다고 생각했습니다!
기존에 사용자의 주소정보가 원래는 같은 테이블이었으나 현재는 분리가 되어있으므로 `@Transactional` 을 걸어서
`Service layer` 에서 사용자의 주소를 회원정보 수정과 동시에 업데이트를 하도록 설정했습니다~

2020-12-25 03:33 UTC, f-lab-dev commented
일반적으로 쇼핑몰도 주문을 할 때 배송지 정보를 수정하면 **자신의 회원정보에도 반영을 할거냐**고 체크박스를 통해 물어봅니다.

이런 flag를 하나 달아서 회원이 동의했을때만 자신의 정보를 수정해주는건 어떨까요?

2020-12-25 03:34 UTC, f-lab-dev commented
제 생각엔 `streetCode`는 만약 추후 참가자에게 이벤트 준비물같은 것들을 발송할 필요가 있다면 필요할 것 같은데 어떠실까요?

2020-12-25 14:57 UTC, Jane096 commented
1. 네!! flag를 달아줘서 좀 더 세부적으로 기능이 동작할 수 있도록 피드백 반영하겠습니다~
2. 추후의 확장성을 고려해볼 필요가 있었네요..! `streetCode` 도 일단 남겨두어 같이 업데이트를 하도록 하겠습니다~

2020-12-25 15:34 UTC, Jane096 commented on src/main/java/com/festa/controller/MemberController.java
> +        }
멘토님 질문이있습니다!

**변경을 할 것인가** 에 대한 체크박스 값을 받아서 체크 했을 경우에 회원정보도 같이 수정하는 것으로 피드백을 반영했습니다. 그런데 만약에 `false` 를 선택했다면 회원정보는 바뀌지 않고 참여자가 이벤트 접수 당시 입력한 주소를 쓴다는 이야기 인데 현재 이벤트 접수 기능에는 주소를 따로 입력해서 넣는 방식을 쓰지 않고 있습니다. (접수할 때는 회원정보의 주소를 그대로 씁니다) 

이럴 경우에 `Participant` 에 주소에 대한 컬럼을 추가해야하고 로직도 바뀔 수 있을 것 같은데 컬럼 추가를 하는게 나을까요?

2020-12-25 15:36 UTC, Jane096 commented
`FirebaseConfig` 를 주석처리 한걸 그대로 commit 하는 바람에 `revert` 를 한번 했습니다!

2020-12-26 02:58 UTC, f-lab-dev commented on src/main/java/com/festa/controller/MemberController.java
> +        }
제 생각에 그 주소는 분리하는게 나을 것 같습니다~ 기획을 어떻게 하냐에 따라 다르겠지만 배송을 필요로 하는거라면 다른 사람의 주소를 넣어야하는 상황도 생길 것 같아서요~

2020-12-26 03:01 UTC, f-lab-dev commented on src/main/java/com/festa/controller/MemberController.java
> +        if(modifyMemberInfo.equals("true")) {
1. `modifyMemberInfo`가 null일 경우 NPE가 날 수 있으므로 순서를 바꿔주는게 좋습니다. `"true".equals(...)`
2. 굳이 이렇게 파라미터를 나누기보다는 `MemberDTO`가 아닌 별도의 Request용 클래스를 만들어서 요청을 받는게 낫지 않을까요? MemberDTO를 통째로 받게 되면 필요없는 데이터도 수신할 수 있게됩니다

2020-12-26 13:36 UTC, Jane096 commented on src/main/java/com/festa/controller/MemberController.java
> +        if(modifyMemberInfo.equals("true")) {
1. NPE 상황이 날 것을 고려하지 못했네요..! 리뷰 반영하겠습니다!!
2. 이젠 `entity` 객체를 따로 만들어 필요한 값만 넘어갈 수 있도록 설정한 것 처럼 회원정보 수정 기능에도 적용시키도록하겠습니다~

2020-12-26 14:03 UTC, Jane096 commented on src/main/java/com/festa/controller/MemberController.java
> +        }
그러면 `member_address` 라는 회원가입 때 넣는 테이블 말고 `participant_address` 라는 테이블을 따로 추가해서 주소를 분리 시키면 될까요?

2020-12-26 14:10 UTC, Jane096 commented on src/main/java/com/festa/controller/MemberController.java
> +            memberService.modifyMemberInfo(memberInfo);
`userModifyInfo` 에도 `true`, `false` 만 들어갈 수 있도록 `userLevel` 설정한 것과 같이  enum으로 관리하는게 나을지 궁금합니다!

2020-12-27 09:17 UTC, Jane096 commented
@Yo0oN  우선 `participant_address` 라는 테이블을 하나 추가하도록 할게요~!

2020-12-27 09:45 UTC, Yo0oN commented
네~ 이후에 erd도 수정하겠습니다~

2020-12-27 12:25 UTC, f-lab-dev commented on src/main/java/com/festa/controller/MemberController.java
> +        if("true".equals(memberInfo.getUserModifyInfo())) {
이제 이렇게 DTO로 받으면 문자열로 받을 필요 없이 boolean으로 받으셔도 되므로 문자열 비교연산을 하지 않으셔도 됩니다

2020-12-27 12:26 UTC, f-lab-dev commented on src/main/java/com/festa/controller/MemberController.java
> +            memberService.modifyMemberInfo(memberInfo);
아래의 리뷰로 답을 대신하겠습니다~
만약 그렇게 한다면 boolean을 enum으로 관리하게 되는데 enum을 사용함으로써 생기는 단점들도 파악해보시면 좋겠네요

2020-12-27 13:57 UTC, Jane096 commented on src/main/java/com/festa/controller/MemberController.java
> +        if("true".equals(memberInfo.getUserModifyInfo())) {
네!! DTO에 해당 컬럼을 boolean 형태로 수정하겠습니다!

2020-12-28 07:38 UTC, f-lab-dev approved these changes

2020-12-28 07:50 UTC, Jane096 commented on src/main/java/com/festa/controller/MemberController.java
> +            memberService.modifyMemberInfo(memberInfo);
저희 프로젝트 상황에서 제일 크게 발생할 수 있는 실수는 `enum` 은 값이 `string` 으로 들어가기 때문에 철자 오타를 냈을 경우 쉽게 오류를 잡아낼 수 없다는 단점이있습니다.

2020-12-28 14:37 UTC, Jane096 commented
@f-lab-dev   `approve` 해주시긴했는데 제가 sql도 추가하고 약간의 수정이 있었습니다! 최종 commit 한것으로 머지해도 괜찮을까요?

2020-12-29 02:05 UTC, f-lab-dev requested changes

2020-12-29 02:05 UTC, f-lab-dev commented on src/main/resources/mapper/MemberMapper.xml
> +        AND districtName = #{districtName}
이런곳에 들여쓰기를 해주면 가독성이 좀 더 좋아질 것 같네요~

2020-12-29 02:26 UTC, Jane096 commented on src/main/resources/mapper/MemberMapper.xml
> +        AND districtName = #{districtName}
네! 전체적으로 `SET` 과 `AND` 는 들여쓰기 하도록 하겠습니다~

2020-12-29 14:37 UTC, Jane096 commented
jasyptConfig에서 오류가 발견되어서 수정을 했습니다!!

2020-12-30 01:53 UTC, f-lab-dev commented on src/main/java/com/festa/FestaApplication.java
> +@EnableEncryptableProperties
원칙적으로는 이런 버그도 이슈를 따로 빼서 작업해주시는게 좋습니다~

2020-12-30 11:35 UTC, Jane096 commented on src/main/java/com/festa/FestaApplication.java
> +@EnableEncryptableProperties
앗..그렇군요 해당 브랜치에서 작업하다 발견한거라 여기에 커밋을 했었네요 다음에 발견된 에러 수정사항은 따로 이슈로 빼서 수정하겠습니다!!

2021-01-02 12:59 UTC, f-lab-dev approved these changes

2021-01-02 14:02 UTC, merged