참여자 목록조회기능 추가, 이벤트 접수기능 수정
f-lab-edu/event-recommender-festa pull request #70
Opened 2020-12-29 15:41 UTC by Jane096

#### 변경사항 

1. 이벤트 상세보기 위치 수정
2. 해당 이벤트의 참여자 목록조회 기능 추가 
3. 이벤트 접수기능에 참여자 주소 insert 부분 누락으로 추가함

#### 질문

자신이 등록한 이벤트에 대해서만 참여자 목록을 볼 수 있도록 설정이 필요할 것 같은데 단순히 sql에서 처리를 해야할지 고민입니다!

2020-12-30 02:02 UTC, f-lab-dev commented on src/main/java/com/festa/controller/EventController.java
> +            return ResponseEntity.badRequest().body(infoOfEvent);
body가 null인데 굳이 보내줄 필요가 있을까요?

2020-12-30 11:34 UTC, Jane096 commented on src/main/java/com/festa/controller/EventController.java
> +            return ResponseEntity.badRequest().body(infoOfEvent);
그러면 빈 객체를 보내기 보단 아예 조건문을 지우거나 예외 메세지를 출력해주는 방향으로 수정해보도록 하겠습니다~

2020-12-30 14:10 UTC, Yo0oN commented on src/main/java/com/festa/controller/EventController.java
> +            return ResponseEntity.badRequest().body(infoOfEvent);
이전에 작성했을 때 상세보기 조회 실패 시 예외보다는 status code를 주는게 나을거같다고 하셔서 그렇게 작성했었습니다. 그 외에도 body를 없이 리턴하면 ResponseEntity<?>로 작성하는건 어떨까 생각했지만, 리턴타입이 정확히 지정해주지 않는것은 좋지 않은 방법인거같아 작성하지 않았는데 와일드카드를 사용하는것도 괜찮은 방법일까요?

2021-01-01 06:22 UTC, f-lab-dev commented on src/main/java/com/festa/controller/EventController.java
> +            return ResponseEntity.badRequest().body(infoOfEvent);
그것때문이셨군요~ 그럼 이런 경우는 상수를 만들어서 리턴해주는게 낫지 않을까요?

2021-01-01 06:23 UTC, f-lab-dev requested changes
추가 코멘트 드린 부분만 확인 부탁드립니다~

2021-01-01 14:17 UTC, Jane096 commented on src/main/java/com/festa/controller/EventController.java
> +            return ResponseEntity.badRequest().body(infoOfEvent);
네!! 그럼 해당 부분은 상수로 만들어서 리턴하는 것으로 리뷰 반영하겠습니다~

2021-01-01 14:49 UTC, Jane096 commented on src/main/java/com/festa/controller/EventController.java
상수로 변경하란 리뷰를 받았었는데요, 조회된 건이 없는데 무언갈 리턴하지 않아도 될 거 같았고, null이 리턴되어도 프론트쪽에서 충분히 제어 가능하다고 생각해서 if 조건문을 삭제하고 리턴타입을 확실히 명시하는 방향으로 변경했습니다!

2021-01-02 13:00 UTC, f-lab-dev approved these changes

2021-01-02 14:01 UTC, merged